apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demo-be
  labels:
    app: app-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-be
  template:
    metadata:
      labels:
        app: app-be
    spec:
      containers:
        - name: app-demo-be
          image: PARAM_IMAGE
          ports:
          - containerPort: 80
