apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demo
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-demo
          image: $IMAGE
          ports:
          - containerPort: 80
